# Generated by Django 4.0.2 on 2022-03-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_locations_alter_pharmacy_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='google_map_link',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='post_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City'),
        ),
    ]
