# Generated by Django 4.0.2 on 2022-03-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_pharmacy_google_map_link_pharmacy_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='county',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='town',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='google_map_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
