# Generated by Django 4.0.2 on 2022-03-28 01:27

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_pharmacy_address_remove_pharmacy_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='google_map_link',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
