# Generated by Django 4.0.2 on 2022-03-28 01:42

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_pharmacy_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='google_map_link',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
