# Generated by Django 4.0.2 on 2022-03-28 02:32

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_pharmacy_google_map_link_alter_pharmacy_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='city',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='google_map_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.locations'),
        ),
    ]
