# Generated by Django 4.0.2 on 2022-03-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rental_delete_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
