# Generated by Django 4.0.2 on 2022-03-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_alter_pharmacy_google_map_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='google_map_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.locations'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
