# Generated by Django 4.0.2 on 2022-03-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('gmap_locatin', models.CharField(max_length=300)),
            ],
        ),
    ]
