# Generated by Django 4.0.2 on 2022-03-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyInfo',
        ),
    ]
